name: Padavan Builder

on:
  repository_dispatch:
    types: [build, release]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.client_payload.targets

    steps:
      - uses: actions/checkout@master

      - name: apt-install
        run: |
          sudo apt update
          sudo apt install -y fakeroot p7zip-full unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
            pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev

      - name: Config
        run: |
          git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel/
          sh dl_toolchain.sh
          mkdir -p /opt/images

      - name: Build
        env:
          targets: ${{ github.event.client_payload.targets }}
          config: ${{ github.event.client_payload.config }}
        run: |
          cd /opt/rt-n56u/trunk/
          for m in $targets; do
            if [ ! -f configs/templates/$m.config ]; then
              echo "configs/templates/$m.config not found"
              continue
            fi
            echo $config | sed 's/ /\n/g' >> configs/templates/$m.config
            fakeroot ./build_firmware_ci $m
            cp -f images/*.trx /opt/images/$m.trx
            ./clear_tree_simple >/dev/null 2>&1
          done

      - name: Prepare
        id: prepare
        run: |
          cd /opt/images
          md5sum *.trx | tee readme.txt
          echo ${{ github.event.client_payload.config }} | sed 's/ /\n/g' >> readme.txt
          echo "::set-output name=tag_name::$(TZ='Asia/Shanghai' date '+v%Y.%m.%d')"

      - name : Upload-artifact
        uses: actions/upload-artifact@master
        with:
          name: Padavan
          path: /opt/images

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event.action == 'release'
        with:
          tag_name: ${{ steps.prepare.outputs.tag_name }}
          body_path: /opt/images/readme.txt
          files: /opt/images/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
