name: Padavan Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: apt-install 
        run: |
          sudo apt update
          sudo apt install -y fakeroot p7zip-full unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
            pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev

      - name: config
        env:
          toolchain_url: "https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz"
        run: |
          chmod a+x build_firmware_modify && cp build_firmware_modify /opt/
          cd /opt && git clone --depth=1 https://github.com/hanwckf/rt-n56u.git
          rm -rf ./rt-n56u/toolchain-mipsel/ && mkdir -p ./rt-n56u/toolchain-mipsel/toolchain-3.4.x && mkdir -p ./images
          wget $toolchain_url && tar -xf mipsel-linux-uclibc.tar.xz -C ./rt-n56u/toolchain-mipsel/toolchain-3.4.x
          cp -f /opt/build_firmware_modify /opt/rt-n56u/trunk/

      - name: build
        env: 
          targets: "MR2600-5.0 MI-MINI"
        run: |
          ls -Alh /opt/rt-n56u && cd /opt/rt-n56u/trunk/
          for m in $targets; do fakeroot ./build_firmware_nohup $m && cp -f images/*.trx /opt/images/$m.trx; ./clear_tree_simple >/dev/null 2>&1; done

      - name: md5sum
        run: cd /opt/images && md5sum *.trx | tee md5sum.txt

      - name : upload
        uses: actions/upload-artifact@master
        with:
          name: Padavan
          path: /opt/images
